### ISSUE TITLE
config.json 运行程序会自动创建还是需要手动创建？

### ISSUE THREAD

**Issue by win1498419293** [Kento-Sec/chatGPT-CodeReview#4]
这个问题是apikey没配置好嘛？尝试让生成config.json文件没成功，提示配置文件创建好但是目录下没有文件，在目录下手动新建/.config/chatGPT-CodeReview/config.json 运行也还是这个报错
![image](https://user-images.githubusercontent.com/44251830/228265028-f8f4510e-d70f-4517-8198-c43c436f9607.png)
![image](https://user-images.githubusercontent.com/44251830/228265101-eb559dba-7f52-4f84-bb9a-17d35f654e70.png)
![image](https://user-images.githubusercontent.com/44251830/228267784-7beaaf81-cc7e-47aa-82f9-d94bd26e5e2b.png)
![image](https://user-images.githubusercontent.com/44251830/228265611-8f629bee-ab41-4081-a1e7-beb53bcf5f95.png)

**Comment by Kento-Sec** [comment]
我没有在windows进行测试。这个模块跟asamf几乎一模一样的。首次执行./chatGPT-CodeReview会自动在/User/用户名/.config/chatGPT-CodeReview/下面生成config.json。你确认一下

**Comment by win1498419293** [comment]
确定如此，config.json创建在/User/用户名/下了，不过还是提示ChatCompletion error: Post "https://api.openai.com/v1/chat/completions": dial tcp [2a03:2880:f10c:283:face:b00c:0:25de]:443: i/o timeout
No choices available in response  （您没有提供 API 密钥。如果您从浏览器访问 API 并提示输入用户名和密码，则需要使用 Bearer auth（即授权：Bearer YOUR_KEY）在授权标头中提供您的 API 密钥，或者作为密码字段（用户名为空） .您可以从 https://platform.openai.com/account/api-keys 获取 API 密钥）这个错误

**Comment by win1498419293** [comment]
> 这个问题是apikey没配置好嘛？尝试让生成config.json文件没成功，提示配置文件创建好但是目录下没有文件，在目录下手动新建/.config/chatGPT-CodeReview/config.json 运行也还是这个报错 ![image](https://user-images.githubusercontent.com/44251830/228265028-f8f4510e-d70f-4517-8198-c43c436f9607.png) ![image](https://user-images.githubusercontent.com/44251830/228265101-eb559dba-7f52-4f84-bb9a-17d35f654e70.png) ![image](https://user-images.githubusercontent.com/44251830/228267784-7beaaf81-cc7e-47aa-82f9-d94bd26e5e2b.png) ![image](https://user-images.githubusercontent.com/44251830/228265611-8f629bee-ab41-4081-a1e7-beb53bcf5f95.png)
